
"""Generate main/pup_trophy_icons.h — 16x16 pixel-art trophy icons.

Each icon is authored below as a 16x16 ASCII grid with a shared palette.
Output matches the img2rgb565.py sprite format: byte-swapped RGB565 pixel
array + 1bpp MSB-first row-major transparency mask, plus an icon-id enum and
lookup tables so the firmware can blit by id.

Usage:  python3 tools/gen_trophy_icons.py        (writes main/pup_trophy_icons.h)
"""

import os
import sys

PALETTE = {
    'W': (0xFF, 0xFF, 0xFF),
    'S': (0xB8, 0xB8, 0xB8),
    'D': (0x40, 0x40, 0x40),
    'K': (0x10, 0x10, 0x10),
    'Y': (0xFF, 0xD6, 0x00),
    'O': (0xFF, 0x6D, 0x00),
    'R': (0xD5, 0x00, 0x00),
    'G': (0x00, 0xC8, 0x53),
    'B': (0x40, 0xC4, 0xF6),
    'P': (0xFF, 0x8A, 0xC2),
    'N': (0x8D, 0x55, 0x24),
    'T': (0xD2, 0xA3, 0x68),
}

ICONS = [
    ("BONE", [
        "................",
        "................",
        "................",
        ".WW..........WW.",
        "WWWW........WWWW",
        "WWWWW......WWWWW",
        ".WWWWWWWWWWWWWW.",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        ".WWWWWWWWWWWWWW.",
        "WWWWW......WWWWW",
        "WWWW........WWWW",
        ".WW..........WW.",
        "................",
        "................",
        "................",
    ]),
    ("BOWL", [
        "................",
        "................",
        "....N.N..N.N....",
        "...N.N.NN.N.N...",
        "................",
        ".RRRRRRRRRRRRRR.",
        "RRRRRRRRRRRRRRRR",
        "RRWWRRRRRRRRRRRR",
        "RRWWRRRRRRRRRRRR",
        ".RRRRRRRRRRRRRR.",
        "..RRRRRRRRRRRR..",
        "...RRRRRRRRRR...",
        "....RRRRRRRR....",
        ".....RRRRRR.....",
        "................",
        "................",
    ]),
    ("PAW", [
        "................",
        "..TT........TT..",
        ".TTTT......TTTT.",
        ".TTTT......TTTT.",
        "..TT..TTTT..TT..",
        ".....TTTTTT.....",
        ".....TTTTTT.....",
        "......TTTT......",
        "....TTTTTTTT....",
        "...TTTTTTTTTT...",
        "..TTTTTTTTTTTT..",
        "..TTTTTTTTTTTT..",
        "..TTTTTTTTTTTT..",
        "...TTTTTTTTTT...",
        "....TTTTTTTT....",
        "................",
    ]),
    ("NOSE", [
        "....G......G....",
        "...G..G..G..G...",
        "....G..G..G.....",
        "...G..G..G..G...",
        "....G......G....",
        "................",
        "...SSSSSSSSSS...",
        "..SSSSSSSSSSSS..",
        ".SSWWSSSSSSSSSS.",
        ".SSWWSSSSSSSSSS.",
        ".SSSSSSSSSSSSSS.",
        "..SSSSSSSSSSSS..",
        "...SSSSSSSSSS...",
        "....SSSSSSSS....",
        "......SSSS......",
        ".......SS.......",
    ]),
    ("TROPHY", [
        "................",
        "..YYYYYYYYYYYY..",
        ".YYYYYYYYYYYYYY.",
        ".Y.YYYYYYYYYY.Y.",
        ".Y.YYYYYYYYYY.Y.",
        ".Y.YYYYYYYYYY.Y.",
        ".YY.YYYYYYYY.YY.",
        "....YYYYYYYY....",
        ".....YYYYYY.....",
        "......YYYY......",
        ".......YY.......",
        ".......YY.......",
        "......YYYY......",
        "....YYYYYYYY....",
        "...YYYYYYYYYY...",
        "................",
    ]),
    ("CAKE", [
        ".......Y........",
        ".......Y........",
        ".......W........",
        ".......W........",
        "...PPPPPPPPPP...",
        "..PPPPPPPPPPPP..",
        "..PWPWPWPWPWPP..",
        "..PPPPPPPPPPPP..",
        "..WWWWWWWWWWWW..",
        "..PPPPPPPPPPPP..",
        "..PPPPPPPPPPPP..",
        ".PPPPPPPPPPPPPP.",
        ".PPPPPPPPPPPPPP.",
        ".PPPPPPPPPPPPPP.",
        "................",
        "................",
    ]),
    ("GHOST", [
        "................",
        ".....WWWWWW.....",
        "....WWWWWWWW....",
        "...WWWWWWWWWW...",
        "..WWWWWWWWWWWW..",
        "..WWKKWWWWKKWW..",
        "..WWKKWWWWKKWW..",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WW.WWW.WWW.W..",
        "..W...W...W.....",
        "................",
    ]),
    ("WAVE", [
        "................",
        ".............B..",
        "............B...",
        ".........B.B....",
        "........B...B...",
        ".....B..B...B...",
        "....B..B..B..B..",
        ".WW.B..B..B..B..",
        ".WW.B..B..B..B..",
        "....B..B..B..B..",
        ".....B..B...B...",
        "........B...B...",
        ".........B.B....",
        "............B...",
        ".............B..",
        "................",
    ]),
    ("LOCK", [
        "....SSSSSS......",
        "...SS....SS.....",
        "...SS....SS.....",
        "...SS....SS.....",
        "...SS...........",
        "...SS...........",
        ".YYYYYYYYYYYY...",
        ".YYYYYYYYYYYY...",
        ".YYYYYYYYYYYY...",
        ".YYYYYKKYYYYY...",
        ".YYYYYKKYYYYY...",
        ".YYYYYYKYYYYY...",
        ".YYYYYYKYYYYY...",
        ".YYYYYYYYYYYY...",
        ".YYYYYYYYYYYY...",
        "................",
    ]),
    ("SHIELD", [
        "................",
        ".GGGGGGGGGGGGGG.",
        ".GGGGGGGGGGGGGG.",
        ".GGGGGGGGGGGGGG.",
        ".GGGGGGGGGWWGGG.",
        ".GGGGGGGGWWGGGG.",
        ".GGWWGGGWWGGGGG.",
        "..GGWWGWWGGGGG..",
        "..GGGWWWGGGGGG..",
        "..GGGGWGGGGGGG..",
        "...GGGGGGGGGG...",
        "...GGGGGGGGGG...",
        "....GGGGGGGG....",
        ".....GGGGGG.....",
        "......GGGG......",
        ".......GG.......",
    ]),
    ("CASE", [
        "................",
        "......SSSS......",
        ".....SS..SS.....",
        ".....SS..SS.....",
        ".NNNNNNNNNNNNNN.",
        ".NNNNNNNNNNNNNN.",
        ".NNNNNNNNNNNNNN.",
        ".NNNNNNYYNNNNNN.",
        ".NNNNNNYYNNNNNN.",
        ".NNNNNNNNNNNNNN.",
        ".NNNNNNNNNNNNNN.",
        ".NNNNNNNNNNNNNN.",
        ".NNNNNNNNNNNNNN.",
        ".NNNNNNNNNNNNNN.",
        "................",
        "................",
    ]),
    ("COUCH", [
        "................",
        "................",
        "................",
        "..BB........BB..",
        ".BBBB......BBBB.",
        ".BBBB......BBBB.",
        ".BBBBBBBBBBBBBB.",
        ".BBBBBBBBBBBBBB.",
        ".BBBDDDDDDDDBBB.",
        ".BBBBBBBBBBBBBB.",
        ".BBBBBBBBBBBBBB.",
        ".BBBBBBBBBBBBBB.",
        "..BB........BB..",
        "..BB........BB..",
        "................",
        "................",
    ]),
    ("BULB", [
        "................",
        ".....YYYYYY.....",
        "....YYYYYYYY....",
        "...YYYYYYYYYY...",
        "...YYYYYYYYYY...",
        "...YYYYYYYYYY...",
        "...YYYYYYYYYY...",
        "....YYYYYYYY....",
        ".....YYYYYY.....",
        ".....YYYYYY.....",
        "......YYYY......",
        "......SSSS......",
        "......SSSS......",
        "......SSSS......",
        ".......SS.......",
        "................",
    ]),
    ("CAM", [
        "................",
        "..SSSSSSSSSSS...",
        ".SSSSSSSSSSSSS..",
        ".SBBSSSSSSSSRS..",
        ".SBBSSSSSSSSSS..",
        ".SSSSSSSSSSSSS..",
        "..SSSSSSSSSSS...",
        ".......SS.......",
        ".......SS.......",
        ".......SS.......",
        ".....SSSSSS.....",
        "....SSSSSSSS....",
        "................",
        "................",
        "................",
        "................",
    ]),
    ("BADGE", [
        ".......YY.......",
        "......YYYY......",
        "..YY..YYYY..YY..",
        "..YYY.YYYY.YYY..",
        "..YYYYYYYYYYYY..",
        "...YYYYYYYYYY...",
        "...YYYYYYYYYY...",
        "...YYYWWYYYYY...",
        "...YYWWWWYYYY...",
        "...YYYWWYYYYY...",
        "....YYYYYYYY....",
        "....YYYYYYYY....",
        ".....YYYYYY.....",
        "......YYYY......",
        ".......YY.......",
        "................",
    ]),
    ("BIRD", [
        "................",
        "................",
        ".........BBB....",
        "........BBBBB...",
        "........BKBBB...",
        ".......BBBBBBO..",
        "..B...BBBBBB....",
        "..BB.BBBBBBB....",
        "..BBBBBBBBBB....",
        "...BBBBBBBBB....",
        "....BBBBBBB.....",
        ".....BBBBB......",
        "......BBB.......",
        "......B.B.......",
        "......B.B.......",
        "................",
    ]),
    ("SPY", [
        "................",
        "................",
        "....DDDDDDDD....",
        "....DDDDDDDD....",
        ".DDDDDDDDDDDDDD.",
        ".DDDDDDDDDDDDDD.",
        "................",
        "..WWWWW..WWWWW..",
        "..W...WWWW...W..",
        "..WWWWW..WWWWW..",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ]),
    ("DOG", [
        "................",
        "..TT........TT..",
        ".TTTT......TTTT.",
        ".TTTTTTTTTTTTTT.",
        ".TTTTTTTTTTTTTT.",
        ".TTKKTTTTTTKKTT.",
        ".TTKKTTTTTTKKTT.",
        ".TTTTTTTTTTTTTT.",
        ".TTTTTKKKKTTTTT.",
        ".TTTTTKKKKTTTTT.",
        "..TTTTTKKTTTTT..",
        "..TTTTTTTTTTTT..",
        "...TTTTTTTTTT...",
        "....TTTTTTTT....",
        "................",
        "................",
    ]),
    ("TAG", [
        "................",
        "....OOOOOOOO....",
        "...OOOOOOOOOO...",
        "..OOOOO..OOOOO..",
        "..OOOOO..OOOOO..",
        "..OOOOOOOOOOOO..",
        "..OOOOOOOOOOOO..",
        "..OOOOOOOOOOOO..",
        "..OOOOOOOOOOOO..",
        "..OOOOOOOOOOOO..",
        "..OOOOOOOOOOOO..",
        "..OOOOOOOOOOOO..",
        "...OOOOOOOOOO...",
        "....OOOOOOOO....",
        "................",
        "................",
    ]),
    ("DRONE", [
        "................",
        ".SS..........SS.",
        "SSSS........SSSS",
        ".SS..........SS.",
        "..S..........S..",
        "..SS........SS..",
        "...SSSSSSSSSS...",
        "....SSSSSSSS....",
        "....SSBBSSSS....",
        "....SSSSSSSS....",
        "...SSSSSSSSSS...",
        "..SS........SS..",
        "..S..........S..",
        ".SS..........SS.",
        "SSSS........SSSS",
        ".SS..........SS.",
    ]),
    ("ZAP", [
        "................",
        ".......YYYYY....",
        "......YYYYY.....",
        ".....YYYYY......",
        "....YYYYY.......",
        "...YYYYYYYYYY...",
        "....YYYYYYYY....",
        ".......YYYY.....",
        "......YYYY......",
        ".....YYYY.......",
        "....YYYY........",
        "...YYY..........",
        "..YYY...........",
        "..YY............",
        "..Y.............",
        "................",
    ]),
    ("TWIN", [
        "................",
        "....DDDDDDDDD...",
        "....DDDDDDDDD...",
        "....DDDDDDDDD...",
        "..WWWWWWWWWWD...",
        "..WWWWWWWWWWD...",
        "..WWWWWWWWWWD...",
        "..WWWWWWWWWWD...",
        "..WWWWWWWWWWD...",
        "..WWWWWWWWWWD...",
        "..WWWWWWWWWWD...",
        "..WWWWWWWWWW....",
        "..WWWWWWWWWW....",
        "................",
        "................",
        "................",
    ]),
    ("KEY", [
        "................",
        "....YYYY........",
        "...YY..YY.......",
        "...YY..YY.......",
        "....YYYY........",
        ".....YY.........",
        ".....YY.........",
        ".....YY.........",
        ".....YYYY.......",
        ".....YY.........",
        ".....YYYY.......",
        ".....YY.........",
        "................",
        "................",
        "................",
        "................",
    ]),
    ("SKULL", [
        "................",
        "....WWWWWWWW....",
        "...WWWWWWWWWW...",
        "..WWWWWWWWWWWW..",
        "..WWWWWWWWWWWW..",
        "..WKKWWWWWWKKW..",
        "..WKKWWWWWWKKW..",
        "..WWWWWWWWWWWW..",
        "..WWWWWKKWWWWW..",
        "..WWWWWWWWWWWW..",
        "...WWWWWWWWWW...",
        "....WWWWWWWW....",
        "....W.W..W.W....",
        "....WWWWWWWW....",
        "................",
        "................",
    ]),
    ("SUN", [
        ".......YY.......",
        ".......YY.......",
        "..Y....YY....Y..",
        "...Y........Y...",
        ".....YYYYYY.....",
        "....YYYYYYYY....",
        "...YYYYYYYYYY...",
        "YY.YYYYYYYYYY.YY",
        "YY.YYYYYYYYYY.YY",
        "...YYYYYYYYYY...",
        "....YYYYYYYY....",
        ".....YYYYYY.....",
        "...Y........Y...",
        "..Y....YY....Y..",
        ".......YY.......",
        ".......YY.......",
    ]),
    ("WARN", [
        ".......OO.......",
        "......OOOO......",
        "......OOOO......",
        ".....OOOOOO.....",
        ".....OOOOOO.....",
        "....OOOKKOOO....",
        "....OOOKKOOO....",
        "...OOOOKKOOOO...",
        "...OOOOKKOOOO...",
        "..OOOOOKKOOOOO..",
        "..OOOOOOOOOOOO..",
        ".OOOOOOKKOOOOOO.",
        ".OOOOOOOOOOOOOO.",
        "OOOOOOOOOOOOOOOO",
        "OOOOOOOOOOOOOOOO",
        "................",
    ]),
    ("PHONE", [
        "................",
        "....WWWWWWWW....",
        "....WWWWWWWW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WBBBBBBW....",
        "....WWWWWWWW....",
        "....WWWWWWWW....",
        "................",
        "................",
    ]),
    ("LAPTOP", [
        "................",
        "................",
        "...SSSSSSSSSS...",
        "...SBBBBBBBBS...",
        "...SBBBBBBBBS...",
        "...SBBBBBBBBS...",
        "...SBBBBBBBBS...",
        "...SBBBBBBBBS...",
        "...SSSSSSSSSS...",
        "..SSSSSSSSSSSS..",
        ".SSSSSSSSSSSSSS.",
        "SSSSSSSSSSSSSSSS",
        "................",
        "................",
        "................",
        "................",
    ]),
    ("WATCH", [
        "................",
        "......DDDD......",
        "......DDDD......",
        "....SSSSSSSS....",
        "...SSSSSSSSSS...",
        "...SSBBBBBBSS...",
        "...SSBBBBBBSS...",
        "...SSBBBBBBSS...",
        "...SSBBBBBBSS...",
        "...SSSSSSSSSS...",
        "....SSSSSSSS....",
        "......DDDD......",
        "......DDDD......",
        "................",
        "................",
        "................",
    ]),
    ("NOTE", [
        "................",
        "......WWWWWWWW..",
        "......WWWWWWWW..",
        "......WW....WW..",
        "......WW....WW..",
        "......WW....WW..",
        "......WW....WW..",
        "......WW....WW..",
        "......WW....WW..",
        "....WWWW..WWWW..",
        "...WWWWW.WWWWW..",
        "...WWWWW.WWWWW..",
        "....WWW...WWW...",
        "................",
        "................",
        "................",
    ]),
    ("CROSS", [
        "................",
        ".....RRRRRR.....",
        ".....RRRRRR.....",
        ".....RRRRRR.....",
        ".....RRRRRR.....",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        ".....RRRRRR.....",
        ".....RRRRRR.....",
        ".....RRRRRR.....",
        ".....RRRRRR.....",
        "................",
    ]),
    ("CAR", [
        "................",
        "................",
        "................",
        "....RRRRRRRR....",
        "...RRBBBBBBRR...",
        "..RRRBBBBBBRRR..",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        ".RRRRRRRRRRRRRR.",
        "..DDDD....DDDD..",
        "..DDDD....DDDD..",
        "................",
        "................",
        "................",
        "................",
    ]),
    ("WRENCH", [
        "................",
        "...SS....SS.....",
        "...SS....SS.....",
        "...SSS..SSS.....",
        "....SSSSSS......",
        ".....SSSS.......",
        ".....SSSS.......",
        ".....SSSS.......",
        ".....SSSS.......",
        ".....SSSS.......",
        ".....SSSS.......",
        ".....SSSS.......",
        "....SSSSSS......",
        "....SSSSSS......",
        "................",
        "................",
    ]),
    ("CHIP", [
        "................",
        "..G..G..G..G....",
        "..G..G..G..G....",
        ".GGGGGGGGGGGG...",
        ".GGGGGGGGGGGG...",
        ".GGDDDDDDDDGG...",
        ".GGDDDDDDDDGG...",
        ".GGDDDDDDDDGG...",
        ".GGDDDDDDDDGG...",
        ".GGGGGGGGGGGG...",
        ".GGGGGGGGGGGG...",
        "..G..G..G..G....",
        "..G..G..G..G....",
        "................",
        "................",
        "................",
    ]),
    ("DOT", [
        "................",
        "....BBBBBBBB....",
        "...B........B...",
        "..B..BBBBBB..B..",
        ".B..B......B..B.",
        ".B.B..BBBB..B.B.",
        ".B.B.BBBBBB.B.B.",
        ".B.B.BBBBBB.B.B.",
        ".B.B..BBBB..B.B.",
        ".B..B......B..B.",
        "..B..BBBBBB..B..",
        "...B........B...",
        "....BBBBBBBB....",
        "................",
        "................",
        "................",
    ]),
    ("CASH", [
        "................",
        "................",
        "................",
        ".GGGGGGGGGGGGGG.",
        ".GGGGGGGGGGGGGG.",
        ".GGWGGGGGGGGWGG.",
        ".GGGGGWWWWGGGGG.",
        ".GGGGGWGGGGGGGG.",
        ".GGGGGWWWWGGGGG.",
        ".GGGGGGGGWGGGGG.",
        ".GGGGGWWWWGGGGG.",
        ".GGWGGGGGGGGWGG.",
        ".GGGGGGGGGGGGGG.",
        ".GGGGGGGGGGGGGG.",
        "................",
        "................",
    ]),
    ("DOOR", [
        "................",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNYYN...",
        "...NNNNNNNYYN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "...NNNNNNNNNN...",
        "................",
        "................",
    ]),
    ("TOWER", [
        ".......RR.......",
        ".......SS.......",
        "......S..S......",
        "......S..S......",
        ".....S.SS.S.....",
        ".....S.SS.S.....",
        "....S..SS..S....",
        "....S.S..S.S....",
        "...S..S..S..S...",
        "...S.S....S.S...",
        "..S..S....S..S..",
        "..S.S......S.S..",
        ".S..S......S..S.",
        ".S.S........S.S.",
        "SSSS........SSSS",
        "................",
    ]),
]

ICON_W = 16
ICON_H = 16

def rgb565be(r, g, b):
    c = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return ((c >> 8) | ((c & 0xFF) << 8)) & 0xFFFF

def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(root, "main", "pup_trophy_icons.h")

    for name, rows in ICONS:
        if len(rows) != ICON_H:
            sys.exit(f"{name}: {len(rows)} rows, want {ICON_H}")
        for i, row in enumerate(rows):
            if len(row) != ICON_W:
                sys.exit(f"{name} row {i}: {len(row)} cols, want {ICON_W}")
            bad = set(row) - set(PALETTE) - {'.'}
            if bad:
                sys.exit(f"{name} row {i}: unknown palette chars {bad}")

    lines = []
    w = lines.append
    w("// Auto-generated by tools/gen_trophy_icons.py — do not edit by hand.")
    w(f"// {len(ICONS)} icons, {ICON_W}x{ICON_H} byte-swapped RGB565 + 1bpp mask.")
    w("#pragma once")
    w("#include <stdint.h>")
    w("")
    w(f"#define PUP_ICON_W {ICON_W}")
    w(f"#define PUP_ICON_H {ICON_H}")
    w("")
    w("typedef enum {")
    for i, (name, _) in enumerate(ICONS):
        w(f"    PUP_ICON_{name} = {i},")
    w("    PUP_ICON_COUNT")
    w("} pup_icon_t;")
    w("")

    for name, rows in ICONS:
        px = []
        mask_bytes = []
        for row in rows:
            bits = 0
            for x, ch in enumerate(row):
                if ch == '.':
                    px.append(0)
                else:
                    px.append(rgb565be(*PALETTE[ch]))
                    bits |= 0x8000 >> x
            mask_bytes.append((bits >> 8) & 0xFF)
            mask_bytes.append(bits & 0xFF)

        w(f"static const uint16_t PUP_ICON_{name}_px[{ICON_W * ICON_H}] = {{")
        for r in range(ICON_H):
            row_px = px[r * ICON_W:(r + 1) * ICON_W]
            w("    " + ",".join(f"0x{v:04X}" for v in row_px) + ",")
        w("};")
        w(f"static const uint8_t PUP_ICON_{name}_mask[{ICON_H * 2}] = {{")
        w("    " + ",".join(f"0x{b:02X}" for b in mask_bytes))
        w("};")
        w("")

    w("static const uint16_t *const PUP_ICON_PX[PUP_ICON_COUNT] = {")
    for name, _ in ICONS:
        w(f"    PUP_ICON_{name}_px,")
    w("};")
    w("")
    w("static const uint8_t *const PUP_ICON_MASK[PUP_ICON_COUNT] = {")
    for name, _ in ICONS:
        w(f"    PUP_ICON_{name}_mask,")
    w("};")
    w("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}: {len(ICONS)} icons")

if __name__ == "__main__":
    main()
