
"""Convert a transparent PNG to a byte-swapped RGB565 + 1bpp mask C header.

The ST7735 panel has no alpha blending, so transparency is preserved with a
companion bitmask: display_draw_image_masked() blits only the opaque pixels and
leaves the rest of the screen untouched (no background is baked in). Pixel words
match display.h's rgb565be() (RGB565 with bytes swapped for the SPI wire).

The image is aspect-fit inside WxH and padded with transparency (never
distorted). ImageMagick (`magick`/`convert`) does decode/resize so we stay
dependency-free (no Pillow).

Usage:
    tools/img2rgb565.py INPUT.png OUTPUT.h SYMBOL WxH [--trim] [--cover]

      WxH      target canvas, e.g. 160x80 or 60x20
      --trim   trim transparent border before fitting (good for badges)
      --cover  scale to FILL the canvas (overflow cropped) instead of
               aspect-fit-with-pad — used for the boot logo
"""
import shutil
import subprocess
import sys

def rgb565be(r: int, g: int, b: int) -> int:
    c = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return ((c >> 8) | (c << 8)) & 0xFFFF

def main() -> int:
    if len(sys.argv) < 5:
        print(__doc__)
        return 2
    src, out, symbol, size = sys.argv[1:5]
    do_trim = "--trim" in sys.argv[5:]
    do_cover = "--cover" in sys.argv[5:]
    w, h = (int(v) for v in size.lower().split("x"))

    magick = shutil.which("magick") or shutil.which("convert")
    if not magick:
        sys.exit("ImageMagick not found (need `magick` or `convert` on PATH)")

    cmd = [magick, src]
    if do_trim:

        cmd += ["-fuzz", "15%", "-trim", "+repage"]

    geom = f"{w}x{h}^" if do_cover else f"{w}x{h}"
    cmd += ["-background", "none", "-filter", "Lanczos",
            "-resize", geom, "-gravity", "center", "-extent", f"{w}x{h}",
            "-unsharp", "0x0.6+0.8+0",
            "-depth", "8", "RGBA:-"]
    raw = subprocess.run(cmd, check=True, stdout=subprocess.PIPE).stdout
    if len(raw) != w * h * 4:
        sys.exit(f"expected {w*h*4} bytes RGBA, got {len(raw)}")

    px = []
    mask = bytearray((w * h + 7) // 8)
    for i in range(w * h):
        r, g, b, a = raw[i * 4:i * 4 + 4]

        opaque = a >= 64
        px.append(rgb565be(r, g, b) if opaque else 0x0000)
        if opaque:
            mask[i >> 3] |= 0x80 >> (i & 7)

    S = symbol.upper()
    with open(out, "w") as f:
        f.write("// Auto-generated by tools/img2rgb565.py — do not edit by hand.\n")
        f.write(f"// Source: {src}  size: {w}x{h}  byte-swapped RGB565 + 1bpp mask\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define {S}_W {w}\n#define {S}_H {h}\n\n")
        f.write(f"static const uint16_t {symbol}[{w * h}] = {{\n")
        for i in range(0, len(px), 12):
            f.write("    " + ",".join(f"0x{v:04X}" for v in px[i:i + 12]) + ",\n")
        f.write("};\n\n")
        f.write(f"// 1 bit/pixel, row-major, MSB-first per byte; 1 = opaque.\n")
        f.write(f"static const uint8_t {symbol}_mask[{len(mask)}] = {{\n")
        for i in range(0, len(mask), 16):
            f.write("    " + ",".join(f"0x{b:02X}" for b in mask[i:i + 16]) + ",\n")
        f.write("};\n")

    print(f"wrote {out}: {w}x{h}, {sum(bin(b).count('1') for b in mask)} opaque px")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
